language: ruby

bundler_args: --without tools

branches:
  only:
    - master
    - travis

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-19mode
  - rbx-2

env:
  matrix:
    - HANDLER="nokogiri"
    - HANDLER="ox"
